# ZSH PATH
export ZSH=$HOME/.oh-my-zsh

# The Theme
ZSH_THEME=agnoster

# Plugins
plugins=(
    git
    colored-man-pages
    zsh-completions
    zsh-syntax-highlighting
    zsh-dircolors-solarized
    zsh-256color
    solarized-man
    zsh-autosuggestions
)

# Add env.sh
source ~/.oh-my-env.sh

source $ZSH/oh-my-zsh.sh
